"""add partners tables

Revision ID: cb0dd356e35b
Revises: 6b1ab85af142
Create Date: 2026-04-04 15:27:17.161961

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0dd356e35b'
down_revision: Union[str, Sequence[str], None] = '6b1ab85af142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('company_website', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('sponsorship_type', sa.Enum('monetary', 'in_kind', 'hybrid', name='sponsorshiptype'), nullable=False),
    sa.Column('offering_writeup', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending_review', 'approved', 'rejected', name='partnerstatus'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)
    op.create_index(op.f('ix_partners_user_id'), 'partners', ['user_id'], unique=True)
    op.create_table('partner_assets',
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('asset_type', sa.Enum('logo', 'banner', 'social_post', 'video', 'document', 'other', name='assettype'), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_assets_id'), 'partner_assets', ['id'], unique=False)
    op.create_index(op.f('ix_partner_assets_partner_id'), 'partner_assets', ['partner_id'], unique=False)
    op.create_table('partner_incentives',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('incentive_type', sa.Enum('monetary', 'in_kind', name='incentivetype'), nullable=False),
    sa.Column('monetary_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_incentives_id'), 'partner_incentives', ['id'], unique=False)
    op.create_index(op.f('ix_partner_incentives_partner_id'), 'partner_incentives', ['partner_id'], unique=False)
    op.create_table('partner_reports',
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_reports_id'), 'partner_reports', ['id'], unique=False)
    op.create_index(op.f('ix_partner_reports_partner_id'), 'partner_reports', ['partner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_reports_partner_id'), table_name='partner_reports')
    op.drop_index(op.f('ix_partner_reports_id'), table_name='partner_reports')
    op.drop_table('partner_reports')
    op.drop_index(op.f('ix_partner_incentives_partner_id'), table_name='partner_incentives')
    op.drop_index(op.f('ix_partner_incentives_id'), table_name='partner_incentives')
    op.drop_table('partner_incentives')
    op.drop_index(op.f('ix_partner_assets_partner_id'), table_name='partner_assets')
    op.drop_index(op.f('ix_partner_assets_id'), table_name='partner_assets')
    op.drop_table('partner_assets')
    op.drop_index(op.f('ix_partners_user_id'), table_name='partners')
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
